const User = require('../models/User')

User.create({name: "João", password: "1234"})
User.create({name: "Maria", password: "4321"})
User.create({name: "José", password: "2345"})
User.create({name: "Ana", password: "5432"})
User.create({name: "Pedro", password: "3456"})
User.create({name: "Amanda", password: "6543"})
User.create({name: "Gustavo", password: "4567"})
User.create({name: "Sofia", password: "7654"})
User.create({name: "Lucas", password: "5678"})
User.create({name: "Júlia", password: "8765"})
User.create({name: "Gabriel", password: "6789"})
User.create({name: "Eduarda", password: "9876"})
